stages:
  - build
  - test
# Only calls make all for the pipeline
job_frontend:
  stage: build
  image: node:latest
  script:
    - make install
    - make build
job_backend:
  stage: build
  image: pmarathi/idb-backend
  script:
  - make test_backend
job_postman:
  stage: build
  image: node:latest
  script:
    - npm install -g newman
    - newman run "LA Homeless Helper API.postman_collection.json" 
jest_tests:
  stage: test
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npm test
acceptance_test:
  stage: test
  image: python:latest
  services:
    - selenium/standalone-chrome
  script:
    - cd frontend/src/__tests__
    - pip3 install --no-cache-dir -r requirements.txt
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update -q -y
    - apt-get -y install google-chrome-stable
    - apt-get --yes install libnss3
    - apt-get --yes install libgconf-2-4
    - apt-get install libx11-xcb1
    - python3 -m unittest acceptance_tests.py

