stages:
  - build
  - test
# Only calls make all for the pipeline
job_frontend:
  stage: build
  image: node:latest
  script:
    - make install
    - make build
job_backend:
  stage: build
  image: pmarathi/idb-backend
  script:
  - make test_backend
job_postman:
  stage: build
  image: node:latest
  script:
    - npm install -g newman
    - newman run "LA Homeless Helper API.postman_collection.json" 
jest_tests:
  stage: test
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npm i react-test-renderer
    - npm test
acceptance_test:
  stage: test
  image: python:3.10.6
  services:
    - selenium/standalone-chrome:latest
  before_script:
    - pip3 install selenium
  script:
    - cd frontend/selenium_tests
    - python3 -m unittest acceptance_tests.py


