stages:
  - build
# Only calls make all for the pipeline
job_frontend:
  stage: build
  image: node:latest
  script:
    - make install
    - make build
job_backend:
  stage: build
  image: pmarathi/idb-backend
  script:
  - make test_backend
