stages:
  - build
  - test
# Only calls make all for the pipeline
job_frontend:
  stage: build
  image: node:latest
  script:
    - make install
    - make build
job_backend:
  stage: build
  image: pmarathi/idb-backend
  script:
  - make test_backend
job_postman:
  stage: build
  image: node:latest
  script:
    - npm install -g newman
    - newman run "LA Homeless Helper API.postman_collection.json" 
jest_tests:
  stage: test
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npm test
acceptance_test:
  stage: test
  image: node:latest
  script:
    - cd frontend
    - cd src
    - cd __tests__
    - python3 -m unittest acceptance_tests.py

